### ISSUE TITLE
Question: caching more than 1 resource with service-worker

### ISSUE THREAD

**Issue by DivadNojnarg** [pedrocoutinhosilva/shiny.pwa#5]
Hi Pedro,

it's not really a package issue but could be a good improvement (I've been doing also quite some work around PWA for shiny, especially [{shinyMobile}](https://unleash-shiny.rinterface.com/mobile-pwa.html)). 

I am wondering how to modify the service-worker so that the offline.html page may call specific css/js files. For instance, below I would need to cache 2 extra assets `framework7-5.7.14/css/framework7.bundle.min.css`, `framework7-5.7.14/js/framework7.bundle.min.js`. 

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Color theme for statusbar (Android only) -->
    <meta name="theme-color" content="#2196f3">
    <!-- Your app title -->
    <title>Oups</title>
    <!-- Path to Framework7 Library Bundle CSS -->
    <link rel="stylesheet" href="framework7-5.7.14/css/framework7.bundle.min.css">
    <!-- Path to your custom app styles-->
  </head>
  <body>
    <!-- App root element -->
    <div id="app">

      <!-- Your main view, should have "view-main" class -->
      <div class="view view-main">
        <!-- Initial Page, "data-name" contains page name -->
        <div data-name="home" class="page">

          <!-- Top Navbar -->
          <div class="navbar">
            <div class="navbar-bg"></div>
            <div class="navbar-inner">
              <div class="title">Offline page</div>
            </div>
          </div>

          <!-- Bottom Toolbar -->
          <div class="toolbar toolbar-bottom">
            <div class="toolbar-inner">
              <!-- Toolbar links -->
              <a href="#" class="link">Link 1</a>
              <a href="#" class="link">Link 2</a>
            </div>
          </div>

          <!-- Scrollable page content -->
          <div class="page-content">
            <p>Welcome to the offline page</p>
          </div>
        </div>
      </div>
    </div>
    <!-- Path to Framework7 Library Bundle JS-->
    <script type="text/javascript" src="framework7-5.7.14/js/framework7.bundle.min.js"></script>
    <!-- Path to your app js-->
    <script>
      var app = new Framework7({
        // App root element
        el: '#app',
        // App Name
        name: 'My App',
        // App id
        id: 'com.myapp.test',
        // Enable swipe panel
        panel: {
          swipe: true,
        },
        // ... other parameters
      });

      var mainView = app.views.create('.view-main');
    </script>
  </body>
</html>
```

I am currently exploring many options like using `cache.addAll` (inspired by [this](https://onsen.io/v2/guide/pwa/tutorial.html#creating-a-serviceworker)) without significant success and debugging service-workers is rather tricky but maybe you have some ideas.

Cheers

David

**Comment by pedrocoutinhosilva** [comment]
Hi David!

I'm assuming your issue might be related not to the caching, but with **loading** from the cache. In the service worker file in shiny.pwa i am actually ignoring all requests for non navigation requests with ` if (event.request.mode === 'navigate')`, so it this case it would require some changes in that part of the code as well.

Between caching the files and making sure we handle requests for all files, it should be enough for dependencies in the offline file to work,

I added a small example of a custom `offline.html` and `pwa-service-worker.js` that showcases those changes:
https://github.com/pedrocoutinhosilva/shiny.pwa/tree/master/examples/pwa%20with%20custom%20template

In particular the service worker file (https://github.com/pedrocoutinhosilva/shiny.pwa/blob/master/examples/pwa%20with%20custom%20template/www/pwa-service-worker.js)

needs a few things, including caching the extra files (like you mentioned):
```
    await cache.add(new Request("styles.css", {cache: 'reload'}));
    await cache.add(new Request("more-styles.css", {cache: 'reload'}));
```
and making sure these are served when offline:
```
  } else {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      const cachedResponse = await cache.match(event.request);
      return cachedResponse;
    })());
```

You can also find a live example here (the template should show when in offline mode):
https://sparktuga.shinyapps.io/pwacustomtemplate/

Let me know if it helps!
Pedro

**Comment by DivadNojnarg** [comment]
Thanks for your answer. I think we are almost there. I get request errors (also in your above demo) when files are not in the cache:

```
The FetchEvent for "https://dgranjon.shinyapps.io/shinyMobileGolemTest/_w_f8fa130c/shared/jquery.min.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

I believe we should check if the cacheResponse is OK:

```js
if (cachedResponse) return cachedResponse;
```

**Comment by pedrocoutinhosilva** [comment]
> I believe we should check if the cacheResponse is OK:

True!

If these dependencies are present in the online version of the page, you might also be able to get away with using a fetch event that does the caching when it gets the network file (something along the lines of what is proposed [here](https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker#cache_then_network)). 

I haven't really played around with this one yet though but it might allow not having to declare all the dependencies

**Comment by DivadNojnarg** [comment]
I got something without errors. All files JS/CSS are here, the JS API is working but the style doesn't apply. Weird but seems more a Framework7 issue. 

![Screenshot 2021-06-21 at 22 59 45](https://user-images.githubusercontent.com/18291543/122827377-8e7f0e80-d2e4-11eb-9f3c-02236e6760a6.png)

**Comment by DivadNojnarg** [comment]
My fetch script. I added:

```js
if (event.request.cache === 'only-if-cached') return;
```

to prevent an error from appearing. This is a bug still ongoing. 

My `else` statement is similar to the `if` (except I removed the preload): I first start from the network and fallback to the cache when necessary:

```js
// also serve other cached assets (not a navigation request)
    event.respondWith(
      (async () => {
        
        try {
          // Always try the network first.
          const networkResponse = await fetch(event.request);
          return networkResponse;
          
        } catch (error) {
          
          const cache = await caches.open(CACHE_NAME);
          const cachedResponse = await cache.match(event.request);
          if (cachedResponse) return cachedResponse;
          
        }
      })()
    );
```

Full fetch code:

```js
self.addEventListener("fetch", (event) => {
  
  // Fix service-worker bug: https://github.com/sveltejs/sapper-template/blob/7e028c825d46f3e633d0378d4d952c9bb1f61068/app/service-worker.js#L61
  if (event.request.cache === 'only-if-cached') return;
  
  // We only want to call event.respondWith() if this is a navigation request
  // for an HTML page.
  if (event.request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          // First, try to use the navigation preload response if it's supported.
          const preloadResponse = await event.preloadResponse;
          if (preloadResponse) {
            return preloadResponse;
          }

          // Always try the network first.
          const networkResponse = await fetch(event.request);
          return networkResponse;
        } catch (error) {
          // catch is only triggered if an exception is thrown, which is likely
          // due to a network error.
          // If fetch() returns a valid HTTP response with a response code in
          // the 4xx or 5xx range, the catch() will NOT be called.
          console.log("Fetch failed; returning offline page instead.", error);

          const cache = await caches.open(CACHE_NAME);
          const cachedResponse = await cache.match(OFFLINE_URL);
          return cachedResponse;
        }
      })()
    );
  } else {
    // also serve other cached assets (not a navigation request)
    event.respondWith(
      (async () => {
        
        try {
          // Always try the network first.
          const networkResponse = await fetch(event.request);
          return networkResponse;
          
        } catch (error) {
          
          const cache = await caches.open(CACHE_NAME);
          const cachedResponse = await cache.match(event.request);
          if (cachedResponse) return cachedResponse;
          
        }
      })()
    );
  }

  // If our if() condition is false, then this fetch handler won't intercept the
  // request. If there are any other fetch handlers registered, they will get a
  // chance to call event.respondWith(). If no fetch handlers call
  // event.respondWith(), the request will be handled by the browser as if there
  // were no service worker involvement.
});
```

This is probably not super optimised nor clean but will allow me to continue the journey ;)

**Comment by pedrocoutinhosilva** [comment]
Awesome! 💯

**Comment by DivadNojnarg** [comment]
After further test, the code only seems to work for chrome (macOS and windows) and android devices. Not supported by iOS and probably ipadOS. Generally the behavior suffers from lack of reproducibility.

**Comment by pedrocoutinhosilva** [comment]
Unfortunately I don't have access to any iOS devices to test it out, but Apple does have some different restrictions when it comes to PWAs, so its not that surprising (I also think they secretly hate PWAs, and try to make them harder to set up :P )

**Comment by DivadNojnarg** [comment]
The issue is quite random. Sometimes, safari caches the files sometimes not. But agreed, Apple does not like PWA.

**Comment by pedrocoutinhosilva** [comment]
Closing for now, let me know if any new issues popup!
