### ISSUE TITLE
service worker not found

### ISSUE THREAD

**Issue by dcaud** [pedrocoutinhosilva/shiny.pwa#8]
When I deploy any of the example apps [here](https://github.com/pedrocoutinhosilva/shiny.pwa/tree/master/examples) to shinyapps.io, I get the following error in DevTools:

> Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://XXX.shinyapps.io/nongolemPWA/') with script ('https://XXX.shinyapps.io/nongolemPWA/pwa-service-worker.js'): A bad HTTP response code (404) was received when fetching the script.

In the `pwa` function I tried with and without an argument for output = "www:

The error also occurs locally, but I see that local deployments may be problematic for various reasons.

Any ideas?

**Comment by dcaud** [comment]
I think this was solved by capitalizing the url in the domain argument of PWA, that is:

instead of "nongolemPWA" it needed to be "NONGOLEMPWA"

It seems that shinyapps.io capitalized the app name (although I didn't when I deployed).

I also removed a trailing slash, that is:

instead of "NONGOLEMPWA/", I used "NONGOLEMPWA"

**Comment by pedrocoutinhosilva** [comment]
Thank you for using shiny.pwa!

I'm glad you managed to get it working, I'll try to improve documentation on this so that its less prone to errors (or at the very least restrictions are better explained)
